language: python
python:
  - "3.5"
cache: pip
# command to install dependencies
install:
  - pip install numpy
  - pip install cython
  - pip install -r requirements-dev.txt
  - pip install -e .[nosql]
# command to run tests
script:
  - make test
